//
// Generated by JTB 1.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All Object visitors must implement this interface.
 */
public interface ObjectVisitor {
   //
   // Object Auto class visitors
   //
   public Object visit(NodeList n, Object argu);

   public Object visit(NodeListOptional n, Object argu);

   public Object visit(NodeOptional n, Object argu);

   public Object visit(NodeSequence n, Object argu);

   public Object visit(NodeToken n, Object argu);


   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( Exp() )+
    * f1 -> <EOF>
    */
   public Object visit(Unit n, Object argu);
   /**
    * f0 -> <IDENT>
    *       | "(" "lambda" "(" ( <IDENT> )* ")" Exp() ")"
    *       | "(" Exp() ( Exp() )* ")"
    *       | "0"
    *       | "(" "+" Exp() "1" ")"
    */
   public Object visit(Exp n, Object argu);
}

