//
// Generated by JTB 1.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <IDENT>
 *       | "(" "lambda" "(" ( <IDENT> )* ")" Exp() ")"
 *       | "(" Exp() ( Exp() )* ")"
 *       | "0"
 *       | "(" "+" Exp() "1" ")"
 */
public class Exp implements Node {
   public NodeChoice f0;

   public Exp(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

