//
// Generated by JTB 1.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ( Exp() )+
 * f1 -> <EOF>
 */
public class Unit implements Node {
   public NodeList f0;
   public NodeToken f1;

   public Unit(NodeList n0, NodeToken n1) {
      f0 = n0;
      f1 = n1;
   }

   public Unit(NodeList n0) {
      f0 = n0;
      f1 = new NodeToken("");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

