/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */

public class ASTIdentifier extends SimpleNode {
  ASTIdentifier(int id) {
    super(id);
  }

  ASTIdentifier(SubScheme p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTIdentifier(id);
  }

  public static Node jjtCreate(SubScheme p, int id) {
      return new ASTIdentifier(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SubSchemeVisitor visitor, Object data) {
    visitor.visit(this, null);
    return null;
  }

  //
  // Manually inserted code for storing identifiers
  //
  // Modified for JJTree 0.3pre5
  //
  private String name;

  void setName(String ident)  { name = ident; }
  String getName()            { return name; }

  public void dump(String prefix) {
    System.out.println(toString(prefix) + ": " + name);
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + " ");
        }
      }
    }
  }
}

/* RCS Information
 * $Id: ASTIdentifier.java,v 1.3 1998/02/12 21:09:10 ktao Exp $
 *
 * $Log: ASTIdentifier.java,v $
 * Revision 1.3  1998/02/12 21:09:10  ktao
 * -Updated for JJTree 0.3pre3 and JavaCC 0.7.
 *
 * Revision 1.2  1997/11/16 20:54:21  ktao
 * -Added RCS info, removed automatically-generated files from repository.
 *
 */

